project:
  output-dir: output
  render:
    - manuscript.qmd

format:
  # Nice HTML output
  html:
    toc: true
    include-in-header:
      - text: |
          <style type="text/css">
          h2.hide {
            display: none;
          }
          </style>
    language: 
      title-block-published: "Latest version"
    shift-heading-level-by: 1
    theme: 
      - zephyr
      - html/custom.scss
    citeproc: false
    filters: 
      - at: pre-render
        path: "_extensions/andrewheiss/wordcount/citeproc.lua"
      - at: pre-render
        path: "_extensions/andrewheiss/wordcount/wordcount.lua"
    lightbox: auto
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300


  # Nice PDF output
  hikmah-pdf:
    cite-method: citeproc

    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    sansfont: "IBM Plex Sans"
    mathfont: "Libertinus Math"
    # linestretch: 1.05

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \everydisplay\expandafter{\the\everydisplay\small}
        
        % Add a little bit of extra space above minipages 
        % for gt table footnotes
        \usepackage{etoolbox}
        \AtBeginEnvironment{minipage}{\vspace{\baselineskip}}


    knitr:
      opts_chunk:
        dev: "cairo_pdf"
